from pandas.io.html import read_html
from selenium import webdriver
import time
import selenium
import csv


driver = webdriver.Chrome()
driver.get('http://fantasy.espn.com/hockey/league/scoreboard?leagueId=43185')
time.sleep(7)
s1 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(2) > section > div > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--away > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s2 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(2) > section > div > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--home > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s3 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(3) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--away > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s4 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(3) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--home > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s5 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(4) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--away > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s6 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(4) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--home > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s7 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(5) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--away > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s8 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(5) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--home > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s9 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(6) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--away > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s10 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(6) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--home > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s11 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(7) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--away > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text
s12 = driver.find_element_by_css_selector('#espn-analytics > div > div.jsx-813185768.shell-container > div.page-container.cf > div.layout.is-full > div > div > div.jsx-653569304.scoreboard.pt4 > div:nth-child(7) > section > div.Scoreboard__RowContainer.flex.flex-column.flex-auto > div > div.jsx-710992233.Scoreboard__Column.Scoreboard__Column--1.ph4.mv4 > div > ul > li.ScoreboardScoreCell__Item.flex.items-center.relative.pb2.ScoreboardScoreCell__Item--home > div.ScoreCell__Score.h4.clr-gray-01.fw-heavy.tar.ScoreCell_Score--scoreboard.pl2').text

print('Matchup 1:', s1,'Vs.', s2,)
print('Matchup 2:', s3,'Vs.', s4,)
print('Matchup 3:', s5,'Vs.', s6,)
print('Matchup 4:', s7,'Vs.', s8,)
print('Matchup 5:', s9,'Vs.', s10,)
print('Matchup 6:', s11,'Vs.', s12,)


driver.close()
